[build]
  # Since this is a static site with no build process needed
  command = "echo 'No build needed - static HTML site'"
  publish = "."

[[headers]]
  # Cache static assets
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  # Cache CSS and JS files longer
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
